apiVersion: v2
name: k8s-loki
description: Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system.
type: application
version: 0.0.0-replaceme
appVersion: "0.0.0-replaceme"
dependencies:
  - name: loki
    version: 5.23.0
    repository: https://grafana.github.io/helm-charts
