apiVersion: v1
values:
  images:
    kubectl: docker.io/bitnami/kubectl:1.28.4
    loki: docker.io/grafana/loki:3.1.1
    lokiCanary: docker.io/grafana/loki-canary:3.1.1
    gateway: docker.io/nginxinc/nginx-unprivileged:1.27-alpine
    sidecar: kiwigrid/k8s-sidecar:1.27.5
patches:
  values.yaml:
    loki:
      kubectlImage:
        registry: "{{ registryFrom .images.kubectl }}"
        repository: "{{ repositoryFrom .images.kubectl }}"
        tag: "{{ tagFrom .images.kubectl }}"
      loki:
        image:
          registry: "{{ registryFrom .images.loki }}"
          repository: "{{ repositoryFrom .images.loki }}"
          tag: "{{ tagFrom .images.loki }}"
      monitoring:
        lokiCanary:
          image:
            registry: "{{ registryFrom .images.lokiCanary }}"
            repository: "{{ repositoryFrom .images.lokiCanary }}"
            tag: "{{ tagFrom .images.lokiCanary }}"
      gateway:
        image:
          registry: "{{ registryFrom .images.gateway }}"
          repository: "{{ repositoryFrom .images.gateway }}"
          tag: "{{ tagFrom .images.gateway }}"
      sidecar:
        image:
          repository: "{{ registryFrom .images.sidecar }}/{{ repositoryFrom .images.sidecar }}"
          tag: "{{ tagFrom .images.sidecar }}"