apiVersion: v1
values:
  images:
    kubectl: docker.io/bitnami/kubectl:1.28.4
    loki: docker.io/grafana/loki:2.9.1
    monitoring: docker.io/grafana/loki:2.9.1
    gateway: docker.io/nginxinc/nginx-unprivileged:1.23-alpine
    sidecar: kiwigrid/k8s-sidecar:1.24.3
patches:
  values.yaml:
    loki:
      kubectlImage:
        registry: "{{ registryFrom .images.kubectl }}"
        repository: "{{ repositoryFrom .images.kubectl }}"
        tag: "{{ tagFrom .images.kubectl }}"
      image:
        registry: "{{ registryFrom .images.loki }}"
        repository: "{{ repositoryFrom .images.loki }}"
        tag: "{{ tagFrom .images.loki }}"
    monitoring:
      lokiCanary:
        registry: "{{ registryFrom .images.monitoring }}"
        repository: "{{ repositoryFrom .images.monitoring }}"
        tag: "{{ tagFrom .images.monitoring }}"
    gateway:
      image:
        registry: "{{ registryFrom .images.gateway }}"
        repository: "{{ repositoryFrom .images.gateway }}"
        tag: "{{ tagFrom .images.gateway }}"
    sidecar:
      image:
        repository: "{{ registryFrom .images.sidecar }}/{{ repositoryFrom .images.sidecar }}"
        tag: "{{ tagFrom .images.sidecar }}"
