{{ $username := "loki-gateway-user" }}
{{ $password :=  randAlphaNum 24  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lokiGatewaySecretName }}
  labels:
    app: ces
    app.kubernetes.io/name: k8s-loki
type: kubernetes.io/basic-auth
data:
  .htpasswd: {{ htpasswd $username $password | b64enc }}
  username: {{ $username | b64enc }}
  password: {{ $password | b64enc }}