{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.lokiGatewaySecretName) -}}
{{ $username := "loki-gateway-user" }}
{{ $password :=  randAlphaNum 24  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lokiGatewaySecretName }}
  labels:
    app: ces
    app.kubernetes.io/name: k8s-loki
  annotations:
    # helm deletes the object if it is present due to above "if not" condition
    # add annotation to keep the object
    helm.sh/resource-policy: keep
type: kubernetes.io/basic-auth
data:
  .htpasswd: {{ htpasswd $username $password | b64enc }}
  username: {{ $username | b64enc }}
  password: {{ $password | b64enc }}
  {{- end -}}