{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "k8s-loki-minio-ingress"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: ces
    app.kubernetes.io/name: k8s-loki
spec:
  podSelector:
    matchLabels:
      app: ces
      app.kubernetes.io/name: k8s-minio
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - read
                  - write
            matchLabels:
              app: ces
              app.kubernetes.io/name: k8s-loki
      ports:
        - protocol: TCP
          port: 9000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "k8s-loki-internal-ingress"
  namespace: {{ $.Release.Namespace }}
  labels:
    app: ces
    app.kubernetes.io/name: k8s-loki
spec:
  podSelector:
    matchLabels:
      app: ces
      app.kubernetes.io/name: k8s-loki
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ces
              app.kubernetes.io/name: k8s-loki
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $.Release.Namespace }}
{{- end}}